import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["PRIORICODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["PRIORICODE_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("PRIORICODE_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  PRIORICODE_AUTO_HEAP_SNAPSHOT: truthy("PRIORICODE_AUTO_HEAP_SNAPSHOT"),
  PRIORICODE_GIT_BASH_PATH: process.env["PRIORICODE_GIT_BASH_PATH"],
  PRIORICODE_CONFIG: process.env["PRIORICODE_CONFIG"],
  PRIORICODE_CONFIG_CONTENT: process.env["PRIORICODE_CONFIG_CONTENT"],
  PRIORICODE_DISABLE_AUTOUPDATE: truthy("PRIORICODE_DISABLE_AUTOUPDATE"),
  PRIORICODE_ALWAYS_NOTIFY_UPDATE: truthy("PRIORICODE_ALWAYS_NOTIFY_UPDATE"),
  PRIORICODE_DISABLE_PRUNE: truthy("PRIORICODE_DISABLE_PRUNE"),
  PRIORICODE_DISABLE_TERMINAL_TITLE: truthy("PRIORICODE_DISABLE_TERMINAL_TITLE"),
  PRIORICODE_SHOW_TTFD: truthy("PRIORICODE_SHOW_TTFD"),
  PRIORICODE_DISABLE_AUTOCOMPACT: truthy("PRIORICODE_DISABLE_AUTOCOMPACT"),
  PRIORICODE_DISABLE_MODELS_FETCH: truthy("PRIORICODE_DISABLE_MODELS_FETCH"),
  PRIORICODE_DISABLE_MOUSE: truthy("PRIORICODE_DISABLE_MOUSE"),
  PRIORICODE_FAKE_VCS: process.env["PRIORICODE_FAKE_VCS"],
  PRIORICODE_SERVER_PASSWORD: process.env["PRIORICODE_SERVER_PASSWORD"],
  PRIORICODE_SERVER_USERNAME: process.env["PRIORICODE_SERVER_USERNAME"],
  PRIORICODE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("PRIORICODE_DISABLE_FFF"),

  // Experimental
  PRIORICODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("PRIORICODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PRIORICODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("PRIORICODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PRIORICODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("PRIORICODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  PRIORICODE_MODELS_URL: process.env["PRIORICODE_MODELS_URL"],
  PRIORICODE_MODELS_PATH: process.env["PRIORICODE_MODELS_PATH"],
  PRIORICODE_DB: process.env["PRIORICODE_DB"],

  PRIORICODE_WORKSPACE_ID: process.env["PRIORICODE_WORKSPACE_ID"],
  PRIORICODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("PRIORICODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get PRIORICODE_DISABLE_PROJECT_CONFIG() {
    return truthy("PRIORICODE_DISABLE_PROJECT_CONFIG")
  },
  get PRIORICODE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("PRIORICODE_EXPERIMENTAL_REFERENCES")
  },
  get PRIORICODE_TUI_CONFIG() {
    return process.env["PRIORICODE_TUI_CONFIG"]
  },
  get PRIORICODE_CONFIG_DIR() {
    return process.env["PRIORICODE_CONFIG_DIR"]
  },
  get PRIORICODE_PURE() {
    return truthy("PRIORICODE_PURE")
  },
  get PRIORICODE_PERMISSION() {
    return process.env["PRIORICODE_PERMISSION"]
  },
  get PRIORICODE_PLUGIN_META_FILE() {
    return process.env["PRIORICODE_PLUGIN_META_FILE"]
  },
  get PRIORICODE_CLIENT() {
    return process.env["PRIORICODE_CLIENT"] ?? "cli"
  },
}
